version: '3.8'
services:

  mongodb:
    container_name: mongo
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog

  graylog:
    container_name: graylog
    image: graylog/graylog:4.0
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_plugins:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=94aefb8be78b2b7c344d11d1ba8a79ef087eceb19150881f69460b8772753263
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - graylog

volumes:
  mongo_data:
  es_data:
  graylog_data:
  graylog_plugins:

networks:
  graylog:
